version: 2.1

orbs:
  # see. https://github.com/sue445/circleci-ruby-orbs/releases
  ruby-orbs: sue445/ruby-orbs@1.6.2

executors:
  ruby:
    docker:
      - image: circleci/ruby

jobs:
  build:
    executor: ruby
    working_directory: ~/tmd45.github.io
    steps:
      - checkout
      - ruby-orbs/bundle-install
      # Compile
      # test as build
      - run: bundle exec middleman build
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor: ruby
    working_directory: ~/tmd45.github.io
    steps:
      - attach_workspace:
          at: .
      - run: echo 'dummy'

workflows:
  tests:
    jobs:
      - build
      - test:
          requires:
            - setup
